### ISSUE TITLE
 nested Bootstrap-tabbed formset doesn't work

### ISSUE THREAD

**Issue by hamdigdoura** [mbertheau/jquery.django-formset#2]
It doesn't work the example of the nested Bootstrap-tabbed formset with (Block -Building -Tenant  ) and It show me this error  :
" Uncaught Error: Empty selector. django-formset.min.js:4
b django-formset.min.js:4
c django-formset.min.js:4
a.fn.djangoFormset django-formset.min.js:4
(anonymous function)"

**Comment by mbertheau** [comment]
Thanks for your report. I'll try to improve the documentation. I probably wasn't careful enough when extracting the example code from our working production code.

**Comment by mbertheau** [comment]
I have updated the readme in 63e4abe. Please let me know if this is still an issue.
