### ISSUE TITLE
Delete button on initial forms

### ISSUE THREAD

**Issue by tapia** [mbertheau/jquery.django-formset#5]
I'm loading a formset, and I see that the initial forms don't have a "Delete" button, like the forms created with `addForm()`, but just the default checkbox.
- Why is it so?
- How can I get the same behaviour with the initial forms and the dynamically created ones? I mean, hide the checkbox, check it when clicking on the button, and hide the whole form.

**Comment by mbertheau** [comment]
@tapia, thank you for letting me know about this issue. The code should replace the delete checkbox with a delete button for initial forms as well (https://github.com/mbertheau/jquery.django-formset/blob/039c24d2974f29a45bbd63909903f29984f0abfe/src/django-formset.coffee#L152), so let's find out why that doesn't happen for you. Could you
1. see if there are any logs or exceptions in the JS console
2. post the HTML code for the formset unprocessed by JavaScript (i.e. after loading the page with JS disabled)

Thanks :)

**Comment by mbertheau** [comment]
@tapia, I'm closing this now for lack of a response. Feel free to reopen when you have time to look into this again.

**Comment by tapia** [comment]
It was my fault, I misunderstood some details of the library. I've got it working now.
